title:       Kanga Kare
author:      Leonard Kiyoshi Bogdonoff
linkedin:    http://www.linkedin.com/pub/leonard-bogdonoff/25/14b/8a6
twitter:     kangakare
github:      kangakare
source:      .
destination: ./_site